### ISSUE TITLE
Installing Postman fails on clean system as non-root

### ISSUE THREAD

**Issue by dmaze** [gantsign/ansible-role-postman#29]
Using:

```
vagrant@vagrant:/vagrant$ ansible-galaxy list -p roles gantsign.postman
- gantsign.postman, 2.1.0
```

Launching the playbook ultimately fails with:

```
...
TASK [gantsign.postman : create Postman installation directory] ****************
changed: [default]

TASK [gantsign.postman : install Postman] **************************************
changed: [default]

TASK [gantsign.postman : write installed version file] *************************
fatal: [default]: FAILED! => {"changed": false, "checksum": "a93d6ac8f0250f5085f76a1f90ac3a9d1177cad6", "msg": "Destination /opt/Postman not writable"}
	to retry, use: --limit @/vagrant/sandbox.retry
```

The install directory isn't world-writeable:

```
vagrant@vagrant:/vagrant$ ls -ld /opt/Postman
drwxr-xr-x 4 root root 4096 Apr 12 18:42 /opt/Postman
```

I'm pretty sure the step at https://github.com/gantsign/ansible-role-postman/blob/master/tasks/main.yml#L99 needs to run with `become: true` to write the version file.

**Comment by freemanjp** [comment]
@dmaze I'm sorry for the late reply. I must have missed the email when you logged the issue and I haven't made any manual changes to this role until now.

Thanks for reporting this issue and identifying the cause. You should find the issue is resolved in the [2.2.0](https://github.com/gantsign/ansible-role-postman/releases/tag/2.2.0) release of this role.
